### ISSUE TITLE
Call to undefined function DigitalCreative\MegaFilter\array_merge_recursive_distinct

### ISSUE THREAD

**Issue by curder** [dcasia/nova-mega-filter#1]
Hi, dcasia:

First of all, thanks for your plugin.

When I install it in my nova backend system, I got an error about `array_merge_recursive_distinct` function does not exist.

- Nova version: 2.7.1

- PHP version: 7.2.17

and I try to search this function on https://php.net, the URL is [array_merge_recursive_distinct](https://www.php.net/manual-lookup.php?pattern=array_merge_recursive_distinct&scope=quickref)

![image](https://user-images.githubusercontent.com/8327004/69527129-9d85c980-0fa6-11ea-8f9f-c488210ec589.png)

Here is the error screenshot:

![image](https://user-images.githubusercontent.com/8327004/69526742-d83b3200-0fa5-11ea-9ac6-959b66d289c3.png)

**Comment by milewski** [comment]
Oops.... my bad.. that is one of a global function i use on my project... I forgot to remove it... fixed on version `v0.1.2`
