### ISSUE TITLE
Filters 3 columns

### ISSUE THREAD

**Issue by omastroberti** [dcasia/nova-mega-filter#102]
Hi! great addon! quick question: is it possible to have 3 columns to place the filters, instead of 2 as now? Thanks

**Comment by milewski** [comment]
Yes, you can call this method:

https://github.com/dcasia/nova-mega-filter/blob/592ff7017634086e2de0ff1bb4ea98a365b3a707/src/MegaFilter.php#L35

**Comment by omastroberti** [comment]
awesome thanks!
