### ISSUE TITLE
Adding the trait breaks belongsTo

### ISSUE THREAD

**Issue by LorenzoSapora** [dcasia/nova-mega-filter#11]
Relating possibly to my last issue (#10), adding `use DigitalCreative\MegaFilter\Column;` and removing `use HasMegaFilterTrait;` in the class, solves the issue. 

I'll investigate after work.

**Comment by LorenzoSapora** [comment]
Looking a little further into the classes, I see my mistake was I needed to call all the columns, then add the method `checked()`, to make them visible. Unless I'm missing something else, I'm going to close this.

**Comment by milewski** [comment]
The method `->checked()` just indicates which columns will be checked by default, and another is `->permanent()` which forces it to always be present on the table but not visible on the columns checkboxes, and the trait `HasMegaFilterTrait` is required, without it this package won't work proparly
