### ISSUE TITLE
Filter sometimes requires two attempts to filter

### ISSUE THREAD

**Issue by LorenzoSapora** [dcasia/nova-mega-filter#15]
![Peek 2020-01-13 17-25](https://user-images.githubusercontent.com/25519274/72277416-caab3b80-3629-11ea-9076-12675ca2b7fa.gif)

(sorry for the weird slow framerate, my capture seems to have halved the framerate of that gif)

**Comment by LorenzoSapora** [comment]
Information: 
- Fresh load of page
- Laravel 5.8.*
- Nova 2.9.3
- Same issue (have to set it twice) when using the default nova filter

**Comment by LorenzoSapora** [comment]
Slight update.

So, this issue appears to only happen when the filters aren't set in the url.

Example:

- Go to `/nova/resources/user`
- Try to filter.
- URL string gets added `?undefined=1&users_filter=W3siv2xhc3MiOiJBcHBcXE5vdmFctEZpbHRlcnNcXFN0YXR1c0ZpbHRlciIsInZhbHVlIjoiMCJ9LHsiY2xhc3MiOiJBcHBcXE5vdmFcXEZpbgRlcnNcXFN0YXR1c0ZpbHRlciIsInZhbHVlIjoiIn1d
`
- Filtering fails
- Try to filter again.
- URL string `?undefined=1&users_filter=W3siv2xhc3MiOiJBcHBcXE5vdmFctEZpbHRlcnNcXFN0YXR1c0ZpbHRlciIsInZhbHVlIjoiMCJ9LHsiY2xhc3MiOiJBcHBcXE5vdmFcXEZpbgRlcnNcXFN0YXR1c0ZpbHRlciIsInZhbHVlIjoiIn1d`

It is exactly the same string, so I assume there's no reload taking place after you select a filter.

**Comment by milewski** [comment]
Are you using the filter in 2 places at the same time? for example, you defined it within this package `filters` section and on the nova `->filters()` method?

**Comment by LorenzoSapora** [comment]
Ah. I am. So I am only placing the filters in this packages filter array? Ok, that makes sense.

I'll also add this piece of information to the README tomorrow.

**Comment by milewski** [comment]
Yeah even natively in nova without this package you can't have the same filter placed twice on the same resource
