### ISSUE TITLE
Actions with showOnTableRow() aren't shown on table row

### ISSUE THREAD

**Issue by LorenzoSapora** [dcasia/nova-mega-filter#17]
I have nothing in my filters/actions, they're both moved within `MegaFilter`. However actions with the method `->showOnTableRow()` only appear in the megafilter, and not inline on the row.

This is a relatively new core method. And for the time being, I'm moving my actions back to actions().

Doesn't work:
```php
          'actions' => [
               (new Actions\AcceptKey)->showOnTableRow(),
          ],
```
Works:
```php
    public function actions(Request $request)
    {
        return [
              (new Actions\AcceptKey)->showOnTableRow(),
        ];
    }
```

**Comment by milewski** [comment]
But that's a bit weird, how to show an "inline" action from this package, if the action is inline I think it should be removed from the MegaFilter actions picker, somewhat be "ignored"

**Comment by LorenzoSapora** [comment]
Agreed, but that specific action is also one that can be mass assigned, so yes, it's valuable inline, but also if someone sees multiple rows that need assigned.

Maybe something to point out in the documentation, with a possible solution of two actions, one dedicated to inline actions, the other to mass assignment. :thinking: 

I'll have a play around with it tonight.

**Comment by milewski** [comment]
This package currently doesn't support conditionally show/hide actions as it does with filters, but if I were to add this functionality for actions too then I think it would make sense having inline actions that only appears once a certain column is active.. so you could have something like:

```php
Column::make('Image')->addAction(DownSampleImage::class),
```
