### ISSUE TITLE
Undefined property: Laravel\Nova\ResourceToolElement::$attribute

### ISSUE THREAD

**Issue by Dontorpedo** [dcasia/nova-mega-filter#2]
Hi the card is shown but the index is only loading with this error:

Undefined property: Laravel\Nova\ResourceToolElement::$attribute {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined property: Laravel\\Nova\\ResourceToolElement::$attribute at C:\\laragon\\www\\invoices\\vendor\\digital-creative\

**Comment by milewski** [comment]
@Dontorpedo can you post the options you gave to the card

**Comment by Dontorpedo** [comment]
i have tried different options like only filters, only columns and only actions but with the same result :(

**Comment by milewski** [comment]
@Dontorpedo the problem might not be with this card can you post your entire nova resource so I can understand what may be the issue

**Comment by milewski** [comment]
Perhaps you found the reason of this issue? closing for now but let me know if there is indeed a bug with this package, thanks!
