### ISSUE TITLE
Feature: column counter

### ISSUE THREAD

**Issue by LorenzoSapora** [dcasia/nova-mega-filter#23]
Visually, when the filter is closed, it's not immediately obvious that columns are unchecked/checked. Especially with the 'saved' status in vue, clicking on another resource, then coming back, an end-user might assume something's wrong, or be unaware they have column filters active.

I'll add this to the list of things I want to work on, so expect a PR at some point in the future. Of course, some pointers would always be helpful if you know how you'd do that in your code base at the moment :)

**Comment by milewski** [comment]
Column management is no longer part of this package, it has been use this instead: https://github.com/dcasia/column-toggler
