### ISSUE TITLE
Feature: make it visually obvious a section is expanded

### ISSUE THREAD

**Issue by LorenzoSapora** [dcasia/nova-mega-filter#24]
![image](https://user-images.githubusercontent.com/25519274/72521847-2fe27500-3854-11ea-8723-88065dc6ab2c.png)

One of these buttons is active. Can you tell me which? Of course not :P

I believe this should just need some styling, as active is already added to the classes. Will look into this today.

**Comment by milewski** [comment]
I do have a class applied to it which makes it darker / ligher depending on state, I think you custom theme set the 2 states to the exacly same color, this is how it looks oh my version:

![image](https://user-images.githubusercontent.com/2874967/72526916-7068df80-38a2-11ea-83b7-ffcecea4975d.png)

**Comment by LorenzoSapora** [comment]
Ah, I have a blanket theme that changes all the tones to the same colour. My mistake, I should have checked/thrown it on a vanilla build. Completely forgot I had done that.
