### ISSUE TITLE
Custom Field not showing

### ISSUE THREAD

**Issue by didix16** [dcasia/nova-mega-filter#28]
Hello. First of all thanks for this packge, it is very useful.

I have the following problem: previously, before apply the mega filter, I had a field which is a Nova Button field (https://github.com/dillingham/nova-button) that allows to render a button like a custom field. However when I have to apply the mega filter, the button does not show anymore.

Is it possible make something to show again the button field in junction with mega filter?

Thanks in advance.

**Comment by milewski** [comment]
You will need to add an attribute manually to the button something like this:

```php
Button::make('Title', 'ADD_THIS'),

// and then on the mega filter column:

Column::make('Title', 'ADD_THIS')
```

**Comment by didix16** [comment]
Thanks It work like a charm!
