### ISSUE TITLE
Megafilter doesn't work on lenses

### ISSUE THREAD

**Issue by LorenzoSapora** [dcasia/nova-mega-filter#30]
When used in a lens, the refresh moves the url back to the base resource.

Steps to reproduce:
- Create user lens
- Add lens to user resource
- Add MegaFilter to lens
- Attempt to check/uncheck any column
- Router moves to original resource (i.e. `resources/users/` from `resources/users/lens/user-verification`)

**Comment by lachie-92** [comment]
Have you had any luck fixing this issue? Im running into the same issue

**Comment by 4n70w4** [comment]
The same issue!
