### ISSUE TITLE
[ REQUEST ] Able customize the Index.vue component

### ISSUE THREAD

**Issue by didix16** [dcasia/nova-mega-filter#31]
Hello.
I need to customize the resource index, to add some different buttons and alter a bit the custom index toolbox.

Since this component is a wrapper component for original Index.vue, I cannot alter the Index.vue to take effect.

So, there's something you can do to enhance the mega filter so we can customize the inner Index.vue ?

Thanks in advance

**Comment by milewski** [comment]
Can you post how you were overinding the original nova index.vue file?

**Comment by didix16** [comment]
Yes.
I was trying to do it as "non best practice", just by taking your project from vendor folder.
I picked up the webpack file and added a new alias ( '@nova' ), pointing to "<rootProject>/nova" path.
Then I modified your ProxyIndex.vue and Megafilter.vue to modify the imports, using the new alias.

The counter part was that I was to recompile again the card.js to take effect...

I am very newbie in the Vue.js world, so I'm asking to you if you could make something that allow us to make changes to Index.vue and still using your mega filter.

These are the changes what I made (In webpack I had to add more "../" to properly reference from vendor folder):

![image](https://user-images.githubusercontent.com/10291092/73338059-0c68f280-4276-11ea-8c2e-2d7e2b3613e4.png)

![image](https://user-images.githubusercontent.com/10291092/73338087-1be83b80-4276-11ea-801e-0154b4348ec7.png)

![image](https://user-images.githubusercontent.com/10291092/73338112-2aceee00-4276-11ea-84a4-2eadbab2e257.png)

**Comment by milewski** [comment]
Hi I thought you were extending the native nova index.vue file directly, but you are actually extending this package index.vue, if you are okay doing that you would be able to do any change you want but you would have to copy the index.vue from nova folder and replace the `ProxyIndex.vue` entirely, but this isn't something I would recommend, as any updates would break your changes, and there is no way I can expose the native `index.vue` from nova or the `ProxyIndex.vue` to be extendable from outside

**Comment by didix16** [comment]
Well the changes on template I made it on the native Index.vue. 
So is not possible then expose the Index.vue component and override it at all..
Well thanks anyway for your time :+1:

**Comment by milewski** [comment]
Yes it's not possible because this package would need to read your extended version and be recompiled... That means I can not recompile this package after the user has already insulated it

**Comment by didix16** [comment]
Understood. I'll see how can edit then. Thanks :+1:
