### ISSUE TITLE
Feature: add belongsTo() support

### ISSUE THREAD

**Issue by phoenixg** [dcasia/nova-mega-filter#32]
Because I don't want to see value, I want to see relation title. Please support it :)

**Comment by milewski** [comment]
Sorry I don't understand what you mean, can you give an example?

**Comment by phoenixg** [comment]
@milewski 

In resource field, commonly I wrote:

```php
BelongsTo::make('My Merchant', 'merchant', \App\Nova\Merchant::class),
```

My `$title = 'display_name';` in Merchant resource class let it display as a sementic meaningful "display_name", not "ID", if I use ` Column::make('Merchant ID', 'merchant_id')->checked()`, it only allow me to use the actual value in the table, not the related "display_name".

**Comment by milewski** [comment]
This doesn't work?

```
Column::make('My Merchant', 'merchant')->checked()
```

**Comment by phoenixg** [comment]
> This doesn't work?
> 
> ```
> Column::make('My Merchant', 'merchant')->checked()
> ```

No, `merchant` is the field of the table, but merchant display name, which I want to use, is not in the table, it's in the relation table that `belongsTo()` can work.

**Comment by milewski** [comment]
Im not really getting what you are saying... if you can post your full nova resource file.. would be easier for me to understand what you mean

**Comment by phoenixg** [comment]
I find a document may explain my need: https://nova.laravel.com/docs/2.0/resources/relationships.html#belongsto

**Comment by milewski** [comment]
I know how that belongs to works, what im not understanding is why this example is not working for you:

```
Column::make('My Merchant', 'merchant')->checked()
```

Because I use this on my projects and it works fine with relationships, the name of the column shown the column selection is exactly what the name you give to the first argument `My Merchant`
