### ISSUE TITLE
Feature: add a filter for input search filter, not the default search

### ISSUE THREAD

**Issue by phoenixg** [dcasia/nova-mega-filter#33]
l want like there is an input box, which binded to a field in the table, when I input a value, it filters out the value in the table.

**Comment by LorenzoSapora** [comment]
That would be more of a standalone tool, as mega-filter is more of a method of displaying filters/columns/actions, over specific filtering methods. Unless @milewski thinks different?

**Comment by milewski** [comment]
I think what he is asking is no different from using a custom filter.. for example:

```php
MegaFilter::make([
    'filters' => [
        new SearchFilter()
    ],
    'columns' => [... ]
])
```

And the `SearchFilter` is just a text input ... nova doesn't have any Free Text filter out of box.. but wouldn't take 10 min to make one..

**Comment by phoenixg** [comment]
@milewsk Yes, it's what I mean.
