### ISSUE TITLE
How to hide card headers?

### ISSUE THREAD

**Issue by 4n70w4** [dcasia/nova-mega-filter#38]
Case: only filters are displayed and there is no need to show these headers and buttons.

They take up a lot of screen space.

![image](https://user-images.githubusercontent.com/38257723/76618652-24e94f80-653a-11ea-94a0-7a09e504b5ce.png)

**Comment by milewski** [comment]
That should be an easy change, can you submit a PR suggesting this change?

**Comment by milewski** [comment]
Latest version now supports nova 4 and all these headers are gone!
