### ISSUE TITLE
How to set custom filtersWidth for each filter?

### ISSUE THREAD

**Issue by 4n70w4** [dcasia/nova-mega-filter#39]
For example: `full` for very big filter and `1/3` for small filters.

**Comment by milewski** [comment]
I haven't created the ability to set width per filter, the configuration would look very wierd for it to work as filters itself doesn't accept a width param natively in Nova

**Comment by 4n70w4** [comment]
I can do it via chrome developer tools:
![image](https://user-images.githubusercontent.com/38257723/76837904-5d43a300-6844-11ea-9626-f5d81cb1eec7.png)
![image](https://user-images.githubusercontent.com/38257723/76838090-bf9ca380-6844-11ea-8e95-1c65733ba367.png)

I don’t see anything strange in similar configuration:
```php
                'filters' => [
                    ['object' =>new QuoteStatusFilter(), 'width' => 'w-full'],
                ],
```
