### ISSUE TITLE
[Question] How to apply the same filter twice? 

### ISSUE THREAD

**Issue by abr4xas** [dcasia/nova-mega-filter#4]
Hey man, great work. 

I only have one question: How to apply the same filter twice? 

Let's say I have a post model that has categories, for example:

- First post with categories: laravel, php
- Second post with categories: laravel, php, javascript
- Third post with categories: laravel, php, vuejs
- Fourth post with categories: tailwind, css

What I need to do is a filter that shows me the posts that contain the laravel category (it shows me three) but I also want to re-filter the results with the posts that contain both the laravel and javascript categories (it shows me one).

**Comment by milewski** [comment]
Isn't it just a matter of querying your post where it has `laravel` or `javascript` ? something like this:

```php
$query->whereHas('categories', fn($query) => $query->whereIn('name', [ 'laravel', 'javascript' ]));
```
