### ISSUE TITLE
Computed fields allways appears whether checkbox is checked or is not

### ISSUE THREAD

**Issue by didix16** [dcasia/nova-mega-filter#41]
Hi,
I have the following problem:

I have a computed field like this:

![image](https://user-images.githubusercontent.com/10291092/76853628-f62aec00-684d-11ea-887b-b2a3c302dcb5.png)

Which its megafilter column is:

![image](https://user-images.githubusercontent.com/10291092/76853709-21add680-684e-11ea-9a23-7e587bb67fe1.png)

And whether the checkbox is checked or not, the column is allways visible...

I need that on checked be visible and on unchecked not visible..

Is there anything I'm not doing well, it's a bug or computed fields are allways rendered ( if so, then could be implement a feature that acts like normal attribute ?)

Thanks in advance

**Comment by milewski** [comment]
You cant use a computed attributed like that, MegaFilter needs to know the name of the field in order to work properly, you can change your code to this:

```php
Text::make('Theme', 'theme')->displayUsing(function(){
  return '.....'
})
```

**Comment by didix16** [comment]
Thanks for answering so fast.
I just make what you say but now the values are just "-":
![image](https://user-images.githubusercontent.com/10291092/76855278-16a87580-6851-11ea-93ea-9dd06c288812.png)

**Comment by milewski** [comment]
is themes a relationship? maybe it should be `$this->resource->themes->first()->name` ? your themes is probably an empty array

**Comment by didix16** [comment]
Yes themes is a relationship. It is not empty because all events have at least one theme and before I  made the change, the values were displayed well.

Also I just make the change for $this->resource->themes->first()->name but the result is still the same

**Comment by milewski** [comment]
If you simply do this doesnt work?

```
Text::make('Theme', 'theme')->displayUsing(function(){
  return 'Test Hello world'
})
```
you see the `Test Hello world` or still `--` ?

**Comment by milewski** [comment]
or you could also try `->resolveUsing()`  instead of `->displayUsing()`

**Comment by didix16** [comment]
> If you simply do this doesnt work?
> 
> ```
> Text::make('Theme', 'theme')->displayUsing(function(){
>   return 'Test Hello world'
> })
> ```
> 
> you see the `Test Hello world` or still `--` ?

Exactly:
![image](https://user-images.githubusercontent.com/10291092/76856291-45275000-6853-11ea-867e-a5a9ab8f5179.png)

**Comment by didix16** [comment]
> or you could also try `->resolveUsing()` instead of `->displayUsing()`

Same result --> '--'

**Comment by milewski** [comment]
Are you using the `use HasMegaFilterTrait;` ?

I have a similar setup and its working for me:

![image](https://user-images.githubusercontent.com/2874967/76856925-52fac680-688f-11ea-977c-a4195682ff3c.png)

**Comment by didix16** [comment]
Yes, I'm using it:
![image](https://user-images.githubusercontent.com/10291092/76857061-fb3f6980-6854-11ea-933f-31151c43bc3d.png)

**Comment by milewski** [comment]
I use it like this:

![image](https://user-images.githubusercontent.com/2874967/76857290-1f6c6c00-6890-11ea-9eb6-68131ded1e87.png)

**Comment by didix16** [comment]
Mmmh, I put it like you but still the same result...

Maybe I have to update the package? My current version is: 
**digital-creative/nova-mega-filter": "^0.2.3**

**Comment by milewski** [comment]
Maybe that's it, the latest version is `v0.2.6`

**Comment by didix16** [comment]
I already update it to v0.2.6 but I have the same problem... :(
I don't know if some package could be interacting with megafilter

Also, I see that the resolveCallback is never been executed. I proved to put a dd("Hello World") inside callback but it is never shown on request

**Comment by milewski** [comment]
I think the problem might not be with this package in your case, this is my test:

![image](https://user-images.githubusercontent.com/2874967/76859267-edf59f80-6893-11ea-8bf9-ed1714630b3b.png)

```php
<?php

declare(strict_types = 1);

namespace App\Nova;

use App\Models\Client as ClientModel;
use DigitalCreative\MegaFilter\Column;
use DigitalCreative\MegaFilter\HasMegaFilterTrait;
use DigitalCreative\MegaFilter\MegaFilter;
use Illuminate\Http\Request;
use Laravel\Nova\Fields\Text;

class Client extends Resource
{
    use HasMegaFilterTrait;

    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = ClientModel::class;

    /**
     * Get the fields displayed by the resource.
     *
     * @param Request $request
     *
     * @return array
     */
    public function fields(Request $request)
    {
        return [

            Text::make('Test', 'test')
                ->resolveUsing(static function () {
                    return 'Hello world';
                }),

        ];
    }

    /**
     * Get the cards available for the request.
     *
     * @param Request $request
     *
     * @return array
     */
    public function cards(Request $request)
    {
        return [
            MegaFilter::make([
                'columns' => [
                    Column::make('Test', 'test'),
                ],
            ]),

        ];
    }

}
```

**Comment by didix16** [comment]
Okey, thank you @milewski . Then, I'll have to keep investigating, but I don't know where to start..

**Comment by didix16** [comment]
Confirmed, I 've updated Laravel and Nova to last versions and now is working as expected.

Thanks for your help @milewski.
