### ISSUE TITLE
Checking/Unchecking columns without effect

### ISSUE THREAD

**Issue by tswonke** [dcasia/nova-mega-filter#42]
I just wanted to try out this package and filters works like expected => great! :-)

But I don't get columns running properly. This is my current configuration:

```php
MegaFilter::make(
                [
                    'filters' => [
                        new KnowledgeBaseStatusFilter(),
                        new KnowledgeBaseTagFilter(),
                    ],
                    'columns'=>[
                        Column::make('Status')->checked(),
                        Column::make('Tags')->checked(),
                        Column::make('Created At')->checked(),
                        Column::make('Updated At')->checked(),
                    ]
                ]
            )
```

Checkboxes for columns do show up. On Checking/Unchecking the list reloads, but there is no visible effect on the columns. Tried Nova 3.4.0 and 3.2.1

Did I miss something?

**Comment by milewski** [comment]
Perhaps you forgot to include the trait? `use HasMegaFilterTrait` ?

**Comment by tswonke** [comment]
sorry... this. is. embarrassing...🤦‍♂️
I think it was a long working day yesterday... 😅

Thanks!
