### ISSUE TITLE
This package and conditional-container in the same class

### ISSUE THREAD

**Issue by codechrisz** [dcasia/nova-mega-filter#47]
Can I use those two packages in the same class?
I try to use them and I get the same error as #37 

```
    use HasConditionalContainer;
    use HasMegaFilterTrait;
```

I try to implement the same workarround, I don't get the error but none of them works.
Is there something that I can do?

**Comment by milewski** [comment]
hi @codechrisz follow the instructions on this comment: https://github.com/dcasia/nova-json-wrapper/issues/4#issuecomment-559796743
