### ISSUE TITLE
[Suggestion] option to save the columns settings

### ISSUE THREAD

**Issue by MohmmedAshraf** [dcasia/nova-mega-filter#5]
Hello, this package is awesome, if you could add more options to be like the WordPress "screen options" so we can toggle any columns we need and the settings will be saved until we need to change them again this will be very cool.

**Comment by milewski** [comment]
@MohmmedAshraf added on version [v0.2.0](https://github.com/dcasia/nova-mega-filter/releases/tag/v0.2.0)
