### ISSUE TITLE
Bug when first load resource

### ISSUE THREAD

**Issue by codegor** [dcasia/nova-mega-filter#51]
If resource firstly loaded Mega filter column doesn't apply, but if change any column all work...

**Comment by jamespavett** [comment]
Any updates on this?

**Comment by slowdream** [comment]
up!

**Comment by khitas** [comment]
I have try all the possible solutions like https://github.com/dcasia/nova-mega-filter/pull/60 but the problem still remains. 
The first load for the MegaFilter colums comes from the browser localStorage. The visible columns for the table in resource index page, comes from the session (if exists), else the columns are loaded from the MegaFilter settings  in Resource's cards. Can you please give a solution ?

**Comment by milewski** [comment]
This is no longer an issue on the latest version!
