### ISSUE TITLE
Checkboxes of columns are "remembered" when I navigate back to list, but wrong columns are shown

### ISSUE THREAD

**Issue by tgilvonas** [dcasia/nova-mega-filter#59]
I have many columns in list, and of them some are checked/displayed by default. I check/uncheck some checkboxes of columns, navigate to another resource, and then I navigate back to resource with MegaFilter (not using back button in browser, but simply clicking on resource link in Nova menu). Checkboxes of columns are "remembered", but default columns are being shown then , and that's wrong. How can I fix that?

`public function cards(Request $request)
    {
        return [
            MegaFilter::make([
                'filters' => [
                    new Filters\LegalStatusFilter(),
                    new Filters\ClientTypeFilter(),
                    new Filters\AccountingAppFilter(),
                    new Filters\UsersFilterForClients(),
                    new Filters\ClientSignedContractAt(),
                    new Filters\ClientTerminatedContractAt(),
                ],
                'columns' => [
                    Column::make(__('Pavadinimas'), 'title')->checked(),
                    Column::make(__('Telefonas'), 'telephone'),
                    Column::make(__('Pagrindinis el. paštas'), 'email'),
                    Column::make(__('Įmonės kodas'), 'company_code'),
                    Column::make(__('Draudėjo kodas'), 'insurer_code'),
                    Column::make(__('Duombazė'), 'database'),
                    Column::make(__('Sutarties pasirašymo data'), 'contract_signed_at'),
                    Column::make(__('Sutarties nutraukimo data'), 'contract_terminated_at'),
                    Column::make(__('PVM mokėtojo kodas'), 'vat_code'),
                    Column::make(__('Tipas'), 'client_types_string'),
                    Column::make(__('Buhalteris'), 'accountants'),
                ],
                'settings' => [
                    'columnsLabel' => __('Kolonos'),
                    'filtersLabel' => __('Filtrai'),
                    'actionsLabel' => __('Veiksmai'),
                    'columnsSectionTitle' => __('Papildomos kolonos'),
                    'filtersSectionTitle' => __('Filtrai'),
                    'actionsSectionTitle' => __('Veiksmai'),
                    'columnsResetLinkTitle' => __('Nustatyti standartines kolonas'),
                    'filtersResetLinkTitle' => __('Nustatyti standartines filtrų reikšmes'),

                ],
            ])
        ];
    }`

**Comment by Santukon** [comment]
Same problem here.

**Comment by milewski** [comment]
The columns portion of this package has been moved away to a different package now: https://github.com/dcasia/column-toggler
