### ISSUE TITLE
Error, when reloading the page

### ISSUE THREAD

**Issue by bernhardh** [dcasia/nova-mega-filter#6]
Thank you for this great nova tool, but I found an error:

When you select (or deselect) any of the columns and the url gets updated to, for example 

```
l/nova/resources/articles?articles_page=3&mega_filter=eyJwb3J0YWxfYmVyZWljaCI6dHJ1ZSwicGFyZW50Ijp0cnVlfQ%3D%3D
```

and you then reload the page (CTRL+R or hit the browser button) the list will not load and you get the following error:

![image](https://user-images.githubusercontent.com/642292/70896008-37fa8b00-1ff0-11ea-8a55-d573c7d562df.png)

**Comment by milewski** [comment]
@bernhardh fixed on version [v0.2.0](https://github.com/dcasia/nova-mega-filter/releases/tag/v0.2.0)
