### ISSUE TITLE
How I can add computed column to Mega columns?

### ISSUE THREAD

**Issue by keizah7** [dcasia/nova-mega-filter#75]
```
Number::make('Match conversion', fn ($offer) => $offer->match_conversion_percent . '%'),

Column::make('Match conversion', ??????)->checked(),
```

instead of

```
Number::make('Match conversion %', 'match_conversion_percent')->sortable(),

Column::make('Match conversion %', 'match_conversion_percent')->checked(),
```

**Comment by milewski** [comment]
Column management is no longer part of this package, use this instead: https://github.com/dcasia/column-toggler, but the computed column should work only if it has an attribute, otherwise there is no way to "toggle" it since we do not know how it is called...
