### ISSUE TITLE
Error: Cannot read property 'concat' of undefined

### ISSUE THREAD

**Issue by yaserzizo** [dcasia/nova-mega-filter#8]
Hi dcasia
thank you for your great plugin
when using actions  if I don't use nova default action the option to select resource rows disappear
and when I click on action button I have below error:

![error](https://user-images.githubusercontent.com/3054670/71540914-b2fd6300-2959-11ea-890f-3fc54e85355d.png)

**Comment by milewski** [comment]
@yaserzizo Fixed on version `v0.2.1`
