### ISSUE TITLE
Nova 4 Support

### ISSUE THREAD

**Issue by milewski** [dcasia/nova-mega-filter#83]
Hi [👋](https://emojipedia.org/waving-hand/)

Unfortunately, the latest update of Nova 4 has brought breaking changes to this package, and it now requires significant updates to make it work. Due to us being an agency relying on client work to keep us going, we are unable at this time to provide maintenance of this package. Rest assured that when we get time, we will upgrade this package to work with Nova 4.

In the meantime, if you would like to contribute to help update this package, don’t hesitate to reach out to us at [hello@digitalcreative.asia](mailto:hello@digitalcreative.asia) to discuss.

Thanks for your support!

**Comment by kylescousin** [comment]
Please upgrade :(

**Comment by IcedElect** [comment]
+

**Comment by LorenzoSapora** [comment]
@IcedElect what a valuable insight, thank you. This will 100% increase the speed of development of this feature, and it's all down to you, and your <ul><li></li></ul>.

**Comment by milewski** [comment]
Hi, the latest version has been rewritten and simplified, now it supports Nova 4 🎉
