### ISSUE TITLE
index view not loading on nova 2.9.2

### ISSUE THREAD

**Issue by cord** [dcasia/nova-mega-filter#9]
Thanks again for your greate packages - took me some time to resolve an issue, where the index view (and filters) just stays on loading / empty without any warning, check out:

https://github.com/laravel/nova-issues/issues/2228

Am not sure if this a generic issue with nova 2.9.2 or some cross incompatibility with other packages

**Comment by milewski** [comment]
Here https://github.com/dcasia/nova-mega-filter/blob/master/resources/js/components/ProxyIndex.vue#L40 I halt the resource table from loading before the package is "ready" are you using anything that could be causing the package to never be into the ready state?

**Comment by cord** [comment]
hm, will the package get into ready state even on resources not using the nova-mega-filter card? Or might this be the issue?

**Comment by milewski** [comment]
Yeah this package does replace the original index.vue from nova so it could potentially affect other pages even thou you are not using this package on other pages

**Comment by milewski** [comment]
And by the way I starting replacing the index.vue file from nova like ~10 days ago with this commit: https://github.com/dcasia/nova-mega-filter/commit/1ab41b075f090a25db3fdcaa70610e3215f898fd 

the previous version was indeed causing halt on the loading from any resource that did not included the mega-filter... your issue in nova was created around ~20 days ago which makes me wonder.. are you using the latest version of this package? 😄

**Comment by cord** [comment]
strange, I run composer update but it did seem to get the latest version. after removing and re-adding the issue seems to be fixed 👍 

Wonder if you would be interested in contributing to an "analytics dashboard" package, which allows us to build configurable dashboards (= resource), see https://github.com/nemrutco/nova-filterable-metrics/issues/1

**Comment by milewski** [comment]
Great! 

Im not sure what you mean by building analytics dashboard, I have seen the issue you referred it and seems you are suggesting a package that has a "mega filter" that once changed applies to everything: cards, resource tables, and/or everything that understand the nova filters, Im not quite understanding what would be the scope of such package, it aims to only filter resource tables? Does it aim to only filter metric cards? Both? what about third party metrics card how that would know how to apply filters to that?

**Comment by cord** [comment]
> Does it aim to only filter metric cards?
yes

> what about third party metrics card how that would know how to apply filters to that?
no idea ;) Maybe it could be done with a trait?

The scope of the analytics dashboard would be to show configurable groups of metrics around the data - a bit like google analytics. The dashboard itself would be a resource detail view, the widgets are morphables attached to the resource item. When setting up a dashboard the user can attach the widgets  and select the item (e.g. customer or product category) to run the metrics on (can all be done with default nova tools).

Missing is the option to have a panel of filters at the top of the page (e.g. a card). when changing the filter  to drill down into the data the metrics would need to reload with the current filter settings. The "filter-changed" event would trigger the reload. the filter parameters are attached to the metrics api url so the developer of the metric can use the filter parameters and adjust the calculation accordingly.

**Comment by milewski** [comment]
I think somehow you would need to do something similar to this package, extend the index.vue and detail.vue from nova, so then you would be able to refresh all the cards at once by calling this method again: https://github.com/laravel/nova-js/blob/master/src/mixins/HasCards.js#L27 and injecting the "filter params" into the `extraCardParams` so then user can receive the filters payload within their card and decide what to do with it
